version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    networks:
      - test-network
    ports:
      - "5433:5432"
networks:
  test-network:
    driver: bridge
